server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/beasties?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:beasties}
    password: ${SPRING_DATASOURCE_PASSWORD:beasties}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: false
    show-sql: false

jwt:
  secret: ${JWT_SECRET:replace_me}
  validity-ms: 3600000 # 1 hour

logging:
  level:
    root: INFO
    com.beasties: DEBUG
